import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { motion } from "framer-motion";
import {
  Calendar,
  CheckCircle2,
  Clock,
  CreditCard,
  Globe2,
  Phone,
  ShieldCheck,
  Send,
  Award,
  GraduationCap,
  Briefcase,
  UserCheck,
  FileText,
  PlaneTakeoff,
  ArrowRight,
} from "lucide-react";
import { PageLayout } from "@/components/site/PageLayout";
import { COUNTRIES_DATA, CONTACT_INFO, CountryData } from "@/lib/site-data";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

// Unique background images for each country
import canadaImg from "@/assets/service-canada.jpg";
import germanyImg from "@/assets/service-schengen.jpg";
import franceImg from "@/assets/hero-about.jpg";
import spainImg from "@/assets/hero-passport.jpg";
import ukImg from "@/assets/service-uk.jpg";
import usaImg from "@/assets/service-us.jpg";
import australiaImg from "@/assets/service-australia.jpg";
import dubaiImg from "@/assets/service-business.jpg";
import defaultHeroImg from "@/assets/hero-country.jpg";

const COUNTRY_HERO_IMAGES: Record<string, string> = {
  germany: germanyImg,
  canada: canadaImg,
  france: franceImg,
  spain: spainImg,
  "united-kingdom": ukImg,
  "united-states": usaImg,
  australia: australiaImg,
  dubai: dubaiImg,
};

const COUNTRY_SPECIFIC_FAQS: Record<string, { question: string; answer: string }[]> = {
  germany: [
    {
      question: "What is the APS certificate and why is it mandatory for Germany?",
      answer:
        "The APS (Akademische Prüfstelle) certificate verifies the authenticity of your educational certificates from Indian universities. It is mandatory for Indian students applying for higher education in Germany before applying for a student visa.",
    },
    {
      question: "How much funds are needed for a German Blocked Account (Sperrkonto)?",
      answer:
        "For standard German student visas, the German Federal Foreign Office currently requires approximately €11,208 to €11,904 in a certified blocked account to cover living expenses for one year.",
    },
    {
      question: "Can students work part-time in Germany?",
      answer:
        "Yes, international students holding a German student visa can work up to 140 full days or 280 half days per year, with attractive minimum wages and post-study work visa (18-month Job Seeker permit) options.",
    },
  ],
  canada: [
    {
      question: "What are the requirements for a Canadian Study Permit?",
      answer:
        "You need an acceptance letter (LOA) with Provincial Attestation Letter (PAL) from a Designated Learning Institution (DLI), proof of financial support (GIC of CAD $20,635+), medical exam, and biometrics.",
    },
    {
      question: "Can I bring my spouse or dependents to Canada?",
      answer:
        "Depending on your program (e.g. Master's / Doctoral degrees or eligible professional programs), spouses may be eligible for an Open Work Permit, and minor children can study at public schools.",
    },
    {
      question: "How does the Post-Graduation Work Permit (PGWP) work?",
      answer:
        "Graduates from eligible Canadian institutions can receive a PGWP valid for up to 3 years, offering a direct pathway to permanent residence through Canadian Experience Class (CEC) and Express Entry.",
    },
  ],
  "united-kingdom": [
    {
      question: "What is a CAS letter for a UK Student Visa?",
      answer:
        "A Confirmation of Acceptance for Studies (CAS) is an electronic reference number generated by your UK university confirming your unconditional offer, course details, tuition fees, and English qualification.",
    },
    {
      question: "What is the UK Graduate Route (Post-Study Work Visa)?",
      answer:
        "The UK Graduate Route allows international students who have successfully completed an undergraduate or master's degree to stay and work (or look for work) in the UK for up to 2 years (3 years for PhD).",
    },
    {
      question: "Is a TB (Tuberculosis) test certificate mandatory for UK from India?",
      answer:
        "Yes, if you are coming from India for a stay exceeding 6 months, you must take a TB test at an approved clinic and submit the medical clearance certificate with your visa application.",
    },
  ],
  "united-states": [
    {
      question: "What is the F-1 Student Visa process for the USA?",
      answer:
        "After receiving your Form I-20 from a SEVP-certified institution, you pay the SEVIS I-901 fee ($350), complete the DS-160 online application, schedule your biometric appointment (OFC) and consular visa interview.",
    },
    {
      question: "What questions are asked in the US Visa Consular Interview?",
      answer:
        "Visa officers evaluate your academic intentions, university choice, funding sources, and strong ties to your home country. VisaEnter provides comprehensive 1-on-1 mock interviews to ensure you pass with confidence.",
    },
    {
      question: "What is OPT (Optional Practical Training) for STEM students?",
      answer:
        "STEM degree graduates in the USA are eligible for a 24-month OPT extension, allowing up to 3 years (36 months) of legal work authorization in the USA post-graduation.",
    },
  ],
  australia: [
    {
      question: "What is the Genuine Student (GS) requirement for Australia?",
      answer:
        "The Genuine Student (GS) criterion assesses your academic progression, personal circumstances, career outcomes, and value of the qualification to confirm genuine study intentions.",
    },
    {
      question: "How much financial capacity is required for Australia Student Visa Subclass 500?",
      answer:
        "Applicants must show proof of 12 months' living costs (approx. AUD $29,710), one-year tuition fees, travel expenses, and Overseas Student Health Cover (OSHC).",
    },
  ],
  dubai: [
    {
      question: "What are the benefits of the Dubai 5-Year Green / Business Visa?",
      answer:
        "The 5-Year Business / Green Visa enables self-sponsorship without a local employer, allowing you to establish companies, invest, purchase real estate, and sponsor family members with easy renewals.",
    },
    {
      question: "How fast is the Dubai Visa processing with VisaEnter?",
      answer:
        "Standard UAE tourist and business visas are processed online within 3 to 5 business days, with express 24-hour delivery options available for urgent travel needs.",
    },
  ],
};

const STEP_ROADMAP = [
  {
    step: "01",
    title: "Profile Assessment",
    duration: "Day 1 - 2",
    desc: "Evaluating academic background, gap years, language test scores, and university acceptance letters.",
    icon: UserCheck,
  },
  {
    step: "02",
    title: "Financial & SOP Prep",
    duration: "Day 3 - 5",
    desc: "Structuring blocked accounts, sponsor affidavits, bank balance certificates, and drafting SOPs.",
    icon: FileText,
  },
  {
    step: "03",
    title: "Online Form Filing",
    duration: "Day 6 - 8",
    desc: "Accurate filing on official embassy portals (VFS, TLS, ImmiAccount, DS-160) with error-free documents.",
    icon: Send,
  },
  {
    step: "04",
    title: "Biometrics & Interview",
    duration: "Day 9 - 12",
    desc: "1-on-1 mock interview preparation with senior counselors and biometric slot scheduling.",
    icon: ShieldCheck,
  },
  {
    step: "05",
    title: "Visa Grant & Departure",
    duration: "Final Stamp",
    desc: "Receiving stamped passport with near 100% approval, plus student housing & flight ticket support.",
    icon: PlaneTakeoff,
  },
];

export const Route = createFileRoute("/countries/$slug")({
  loader: ({ params }) => {
    const country = COUNTRIES_DATA.find((c) => c.slug === params.slug);
    if (!country) throw notFound();
    return { country };
  },
  head: ({ loaderData }) => ({
    meta: loaderData
      ? [
          { title: loaderData.country.metaTitle },
          { name: "description", content: loaderData.country.metaDescription },
          { property: "og:title", content: loaderData.country.metaTitle },
          { property: "og:description", content: loaderData.country.metaDescription },
        ]
      : [{ title: "Country Visa Services — VisaEnter" }],
  }),
  component: CountryPage,
  notFoundComponent: () => (
    <PageLayout>
      <div className="py-40 text-center">
        <h1 className="text-4xl font-bold">Country Not Found</h1>
        <p className="mt-2 text-muted-foreground">The requested country guide does not exist.</p>
        <Link
          to="/"
          className="mt-6 inline-block rounded-full gradient-primary px-6 py-2.5 text-sm font-bold text-white"
        >
          Back to Home
        </Link>
      </div>
    </PageLayout>
  ),
});

function CountryPage() {
  const { country } = Route.useLoaderData<{ country: CountryData }>();
  const otherCountries = COUNTRIES_DATA.filter((c) => c.slug !== country.slug).slice(0, 4);
  const heroImage = COUNTRY_HERO_IMAGES[country.slug] || defaultHeroImg;
  const faqs = COUNTRY_SPECIFIC_FAQS[country.slug] || [
    {
      question: `What is the processing time for a ${country.name} visa?`,
      answer: `Processing typically takes ${country.processingTime}. VisaEnter handles complete document preparation to avoid any embassy delays.`,
    },
    {
      question: `What are the financial requirements for ${country.name}?`,
      answer: `You must show proof of financial sufficiency (bank statements, sponsor affidavits, or blocked funds) covering your tuition and living costs.`,
    },
    {
      question: `Does VisaEnter provide interview and appointment booking for ${country.name}?`,
      answer: `Yes! We manage appointment scheduling at VFS/embassy portals, provide mock interview coaching, and structure your document dossier.`,
    },
  ];

  return (
    <PageLayout>
      {/* 1. Hero with Single-Line Gradient Title & Balanced Font Size */}
      <section className="relative h-[60vh] min-h-[440px] max-h-[580px] w-full overflow-hidden bg-slate-950 flex items-center">
        <div
          className="absolute inset-0 bg-cover bg-center transition-all duration-700"
          style={{ backgroundImage: `url(${heroImage})` }}
          aria-hidden
        />
        {/* Darkening Gradient Overlay */}
        <div
          className="absolute inset-0"
          style={{
            background:
              "linear-gradient(180deg, rgba(15, 23, 42, 0.72) 0%, rgba(15, 23, 42, 0.9) 100%)",
          }}
          aria-hidden
        />

        <div className="relative z-10 mx-auto max-w-7xl px-6 text-white pt-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-4xl"
          >
            {/* Country Category Pill */}
            <span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3.5 py-1 text-xs font-semibold uppercase tracking-[0.2em] backdrop-blur-md mb-4">
              <span className="h-2 w-2 rounded-full animate-pulse bg-emerald-400" />
              Immigration &amp; Visa Advisory
            </span>

            {/* Single-Line Gradient Title with Decreased Balanced Size */}
            <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-5xl font-extrabold tracking-tight leading-tight">
              <span className="text-white">{country.name} </span>
              <span className="text-gradient">Visa Services</span>
            </h1>

            {/* Subtitle */}
            <p className="mt-3 text-base md:text-lg text-white/85 leading-relaxed font-light max-w-2xl">
              {country.tagline} — Expert assistance with near 100% approval rate by VisaEnter.
            </p>

            {/* Quick action buttons */}
            <div className="mt-6 flex flex-wrap gap-4">
              <a
                href="#apply-form"
                className="inline-flex items-center gap-2 rounded-full gradient-primary px-6 py-3 text-xs md:text-sm font-bold text-white shadow-lg hover:shadow-xl hover:scale-105 transition-all"
              >
                Start Your Application <ArrowRight className="h-4 w-4" />
              </a>
              <a
                href={CONTACT_INFO.whatsappHref}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-full border border-white/30 bg-white/10 px-6 py-3 text-xs md:text-sm font-bold text-white backdrop-blur-md hover:bg-white/20 transition-all"
              >
                Chat on WhatsApp
              </a>
            </div>
          </motion.div>
        </div>
      </section>

      {/* 2. Key Metrics Bar */}
      <section className="py-10 bg-secondary/30 border-y">
        <div className="mx-auto max-w-7xl px-6">
          <div className="grid gap-6 sm:grid-cols-3">
            {[
              { icon: Clock, label: "Processing Time", value: country.processingTime },
              { icon: CreditCard, label: "Approx. Visa Fee", value: country.visaFee },
              { icon: Calendar, label: "Visa Validity", value: country.validityPeriod },
            ].map((m, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 15 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                whileHover={{ y: -4 }}
                className="rounded-3xl border border-border/80 bg-white p-6 shadow-sm flex items-center gap-5 hover:shadow-card transition-all"
              >
                <div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl gradient-primary text-white shadow-md">
                  <m.icon className="h-5 w-5" />
                </div>
                <div>
                  <div className="text-xs font-bold uppercase text-muted-foreground tracking-wider">
                    {m.label}
                  </div>
                  <div className="text-lg font-bold text-foreground mt-0.5">{m.value}</div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* 3. Main Content Grid (Overview & Checklist) */}
      <section className="py-20 bg-white">
        <div className="mx-auto max-w-7xl px-6">
          <div className="grid gap-12 lg:grid-cols-3">
            {/* Left 2 Cols: Details & Requirements */}
            <div className="lg:col-span-2 space-y-14">
              <div>
                <span
                  className="text-xs font-extrabold uppercase tracking-[0.25em]"
                  style={{ color: "var(--primary)" }}
                >
                  COMPREHENSIVE GUIDANCE
                </span>
                <h2 className="mt-2 text-2xl md:text-4xl font-bold text-foreground">
                  About {country.name} Visa Assistance
                </h2>
                <p className="mt-4 text-muted-foreground leading-relaxed text-base">
                  {country.description}
                </p>
              </div>

              {/* Visa Pathways for this Country */}
              <div>
                <h3 className="text-xl md:text-2xl font-bold text-foreground mb-6">
                  Available Visa Pathways for {country.name}
                </h3>
                <div className="grid gap-4 sm:grid-cols-2">
                  {[
                    {
                      icon: GraduationCap,
                      title: "Student Visa",
                      desc: "For undergraduate, master's, diploma and research admissions with work permits.",
                    },
                    {
                      icon: Briefcase,
                      title: "Work & Employment Permit",
                      desc: "For skilled professionals, job seekers, and intra-company transferees.",
                    },
                    {
                      icon: Globe2,
                      title: "Tourist & Visitor Visa",
                      desc: "For leisure, vacation, visiting friends, and short-term cultural exploration.",
                    },
                    {
                      icon: Award,
                      title: "Business & Investor Visa",
                      desc: "For corporate meetings, trade fairs, company setup, and multi-entry investor visas.",
                    },
                  ].map((path, idx) => (
                    <motion.div
                      key={idx}
                      initial={{ opacity: 0, y: 15 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: idx * 0.08 }}
                      whileHover={{ y: -4 }}
                      className="rounded-2xl border border-border/80 bg-secondary/20 p-5 shadow-sm hover:shadow-card hover:border-primary/30 transition-all"
                    >
                      <div className="grid h-10 w-10 place-items-center rounded-xl gradient-primary text-white mb-3">
                        <path.icon className="h-5 w-5" />
                      </div>
                      <h4 className="font-bold text-foreground text-base">{path.title}</h4>
                      <p className="mt-1.5 text-xs text-muted-foreground leading-relaxed">
                        {path.desc}
                      </p>
                    </motion.div>
                  ))}
                </div>
              </div>

              {/* Requirements Checklist */}
              <div>
                <h3 className="text-xl md:text-2xl font-bold text-foreground">
                  Key Requirements &amp; Checklist
                </h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Our immigration experts assist you in gathering, verifying, and translating all necessary documents to build a solid case.
                </p>

                <div className="mt-6 space-y-3">
                  {country.requirements.map((req, idx) => (
                    <motion.div
                      key={idx}
                      initial={{ opacity: 0, x: -15 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: idx * 0.05 }}
                      whileHover={{ x: 4 }}
                      className="flex items-start gap-3.5 p-4 rounded-2xl border bg-card shadow-sm hover:border-primary/40 transition-all"
                    >
                      <CheckCircle2
                        className="h-5 w-5 shrink-0 mt-0.5"
                        style={{ color: "var(--accent)" }}
                      />
                      <span className="text-sm font-medium text-foreground">{req}</span>
                    </motion.div>
                  ))}
                </div>
              </div>

              {/* Trust Banner Callout */}
              <div className="rounded-3xl gradient-primary p-8 text-white shadow-card">
                <div className="flex items-center gap-3 mb-2">
                  <ShieldCheck className="h-6 w-6" />
                  <span className="text-sm font-bold uppercase tracking-wider">
                    VisaEnter Guarantee
                  </span>
                </div>
                <h3 className="text-2xl font-bold">15+ Years Handling {country.name} Cases</h3>
                <p className="mt-2 text-sm text-white/90 leading-relaxed">
                  Whether you have previous visa denials, gap years, or complex financial profiles, our Bangalore team crafts a strategic dossier to maximize your approval probability.
                </p>
                <div className="mt-6">
                  <a
                    href={CONTACT_INFO.phoneHref}
                    className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-2.5 text-sm font-bold text-foreground shadow hover:bg-white/90 transition-all"
                  >
                    <Phone className="h-4 w-4" /> Call Specialist: {CONTACT_INFO.phone}
                  </a>
                </div>
              </div>
            </div>

            {/* Right Col: Consultation / Application Form */}
            <div id="apply-form">
              <div className="rounded-3xl border border-border/80 bg-white p-7 shadow-card sticky top-24">
                <h3 className="text-xl font-bold text-foreground">Apply for {country.name}</h3>
                <p className="mt-1 text-xs text-muted-foreground">
                  Get a personalized roadmap for your {country.name} visa application.
                </p>

                <form
                  onSubmit={(e) => {
                    e.preventDefault();
                    alert(`Thank you! Our ${country.name} visa specialist will reach out shortly.`);
                  }}
                  className="mt-6 space-y-4"
                >
                  <div>
                    <label className="block text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1">
                      Full Name *
                    </label>
                    <input
                      required
                      placeholder="Your name"
                      className="w-full rounded-xl border bg-background px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1">
                      Phone Number *
                    </label>
                    <input
                      required
                      type="tel"
                      placeholder="+91-XXXXX XXXXX"
                      className="w-full rounded-xl border bg-background px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1">
                      Email Address *
                    </label>
                    <input
                      required
                      type="email"
                      placeholder="you@email.com"
                      className="w-full rounded-xl border bg-background px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1">
                      Visa Category
                    </label>
                    <select className="w-full rounded-xl border bg-background px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">
                      <option>Student Visa</option>
                      <option>Tourist / Visitor Visa</option>
                      <option>Business Visa</option>
                      <option>Work / Job Seeker Visa</option>
                      <option>Family / Spouse Visa</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1">
                      Case Notes / Questions
                    </label>
                    <textarea
                      rows={3}
                      placeholder="Course intake, travel dates, or previous rejection history..."
                      className="w-full rounded-xl border bg-background px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20 resize-none"
                    />
                  </div>

                  <button
                    type="submit"
                    className="w-full rounded-xl gradient-primary py-3 text-sm font-bold text-white shadow-md hover:scale-[1.02] transition-all flex items-center justify-center gap-2"
                  >
                    <Send className="h-4 w-4" /> Book Free Assessment
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 4. STEP-BY-STEP PATHWAY (Polished 5-Step Connected Roadmap) */}
      <section className="py-24 bg-secondary/30 relative overflow-hidden">
        <div className="mx-auto max-w-7xl px-6">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <span
              className="text-xs font-extrabold uppercase tracking-[0.25em]"
              style={{ color: "var(--primary)" }}
            >
              STEP-BY-STEP PATHWAY
            </span>
            <h2 className="mt-2 text-3xl md:text-5xl font-bold text-foreground">
              How We Process Your <span className="text-gradient">{country.name} Visa</span>
            </h2>
            <p className="mt-4 text-base text-muted-foreground">
              A transparent, structured 5-step roadmap ensuring fast turnaround and zero delays.
            </p>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-5 relative">
            {STEP_ROADMAP.map((st, i) => (
              <motion.div
                key={st.step}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{
                  duration: 0.5,
                  delay: i * 0.1,
                }}
                whileHover={{
                  y: -8,
                  scale: 1.02,
                }}
                className="group relative rounded-3xl border border-border/80 bg-white p-6 shadow-sm hover:shadow-glow-primary hover:border-primary/50 transition-all duration-300 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <span
                      className="inline-flex items-center justify-center rounded-full px-3 py-0.5 text-xs font-extrabold text-white shadow-sm"
                      style={{ backgroundColor: "var(--primary)" }}
                    >
                      Step {st.step}
                    </span>
                    <span className="text-[10px] font-extrabold uppercase rounded-full bg-secondary px-2 py-0.5 text-muted-foreground">
                      {st.duration}
                    </span>
                  </div>

                  <div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary group-hover:gradient-primary group-hover:text-white transition-all duration-300 mb-4">
                    <st.icon className="h-6 w-6" />
                  </div>

                  <h4 className="font-bold text-base text-foreground group-hover:text-primary transition-colors mb-2">
                    {st.title}
                  </h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {st.desc}
                  </p>
                </div>

                <div className="mt-6 pt-3 border-t flex items-center justify-between text-[11px] font-bold text-primary">
                  <span>Milestone {st.step}</span>
                  <span className="group-hover:translate-x-1 transition-transform">→</span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* 5. Country Specific FAQs */}
      <section className="py-20 bg-white">
        <div className="mx-auto max-w-4xl px-6">
          <div className="text-center mb-14">
            <span
              className="text-xs font-extrabold uppercase tracking-[0.25em]"
              style={{ color: "var(--primary)" }}
            >
              FREQUENTLY ASKED
            </span>
            <h2 className="mt-2 text-3xl md:text-4xl font-bold text-foreground">
              {country.name} Visa FAQs
            </h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Answers to the most common queries regarding {country.name} visas.
            </p>
          </div>

          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, idx) => (
              <AccordionItem
                key={idx}
                value={`faq-${idx}`}
                className="rounded-2xl border border-border/80 px-6 py-1 shadow-sm data-[state=open]:shadow-md data-[state=open]:border-primary/40 transition-all"
              >
                <AccordionTrigger className="text-left font-bold text-base hover:text-primary transition-colors">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-sm text-muted-foreground leading-relaxed pt-2 pb-4">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* 6. Other Destinations (Cards with Destination Photos) */}
      <section className="py-20 bg-secondary/30 border-t">
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-10">
            <div>
              <span
                className="text-xs font-extrabold uppercase tracking-[0.25em]"
                style={{ color: "var(--primary)" }}
              >
                EXPLORE MORE
              </span>
              <h3 className="mt-1 text-2xl md:text-3xl font-bold text-foreground">
                Other Popular Destinations
              </h3>
            </div>
            <Link to="/" className="text-xs font-bold text-primary hover:underline">
              View All Countries →
            </Link>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {otherCountries.map((c) => {
              const cImg = COUNTRY_HERO_IMAGES[c.slug] || defaultHeroImg;
              return (
                <Link
                  key={c.slug}
                  to="/countries/$slug"
                  params={{ slug: c.slug }}
                  className="rounded-3xl border border-border/80 bg-white overflow-hidden shadow-sm hover:shadow-glow-primary hover:border-primary/40 hover:-translate-y-1.5 transition-all flex flex-col justify-between group"
                >
                  {/* Photo Header */}
                  <div className="relative h-40 overflow-hidden">
                    <img
                      src={cImg}
                      alt={c.name}
                      className="h-full w-full object-cover group-hover:scale-110 transition-transform duration-500"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent" />
                    <div className="absolute top-3 left-3">
                      <span className="rounded-full bg-white/20 backdrop-blur-md border border-white/20 px-2.5 py-0.5 text-[10px] font-extrabold text-white uppercase tracking-wider">
                        Visa Services
                      </span>
                    </div>
                    <div className="absolute bottom-2.5 left-3.5 right-3.5">
                      <h4 className="font-extrabold text-lg text-white drop-shadow">
                        {c.name}
                      </h4>
                    </div>
                  </div>

                  {/* Body */}
                  <div className="p-5 flex-1 flex flex-col justify-between">
                    <p className="text-xs text-muted-foreground line-clamp-2">{c.tagline}</p>
                    <div className="mt-4 pt-3 border-t flex items-center justify-between text-xs font-bold text-primary">
                      <span>Explore Requirements</span>
                      <span className="group-hover:translate-x-1 transition-transform">→</span>
                    </div>
                  </div>
                </Link>
              );
            })}
          </div>
        </div>
      </section>
    </PageLayout>
  );
}
