import { useState, useRef, useEffect } from "react";
import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import {
  Calendar,
  CheckCircle2,
  Clock,
  CreditCard,
  Globe2,
  Phone,
  ShieldCheck,
  Send,
  Award,
  GraduationCap,
  Briefcase,
  UserCheck,
  FileText,
  PlaneTakeoff,
  ArrowRight,
  Loader2,
  Check,
  ChevronDown,
  AlertCircle,
  Sparkles,
} from "lucide-react";
import { PageLayout } from "@/components/site/PageLayout";
import { COUNTRIES_DATA, CONTACT_INFO, CountryData } from "@/lib/site-data";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

// Unique background images for each country
import canadaImg from "@/assets/service-canada.jpg";
import germanyImg from "@/assets/service-schengen.jpg";
import franceImg from "@/assets/hero-about.jpg";
import spainImg from "@/assets/hero-passport.jpg";
import ukImg from "@/assets/service-uk.jpg";
import usaImg from "@/assets/service-us.jpg";
import australiaImg from "@/assets/service-australia.jpg";
import dubaiImg from "@/assets/service-business.jpg";
import defaultHeroImg from "@/assets/hero-country.jpg";

const COUNTRY_HERO_IMAGES: Record<string, string> = {
  germany: germanyImg,
  canada: canadaImg,
  france: franceImg,
  spain: spainImg,
  "united-kingdom": ukImg,
  "united-states": usaImg,
  australia: australiaImg,
  dubai: dubaiImg,
};

const COUNTRY_SPECIFIC_FAQS: Record<string, { question: string; answer: string }[]> = {
  germany: [
    {
      question: "What is the APS certificate and why is it mandatory for Germany?",
      answer:
        "The APS (Akademische Prüfstelle) certificate verifies the authenticity of your educational certificates from Indian universities. It is mandatory for Indian students applying for higher education in Germany before applying for a student visa.",
    },
    {
      question: "How much funds are needed for a German Blocked Account (Sperrkonto)?",
      answer:
        "For standard German student visas, the German Federal Foreign Office currently requires approximately €11,208 to €11,904 in a certified blocked account to cover living expenses for one year.",
    },
    {
      question: "Can students work part-time in Germany?",
      answer:
        "Yes, international students holding a German student visa can work up to 140 full days or 280 half days per year, with attractive minimum wages and post-study work visa (18-month Job Seeker permit) options.",
    },
  ],
  canada: [
    {
      question: "What are the requirements for a Canadian Study Permit?",
      answer:
        "You need an acceptance letter (LOA) with Provincial Attestation Letter (PAL) from a Designated Learning Institution (DLI), proof of financial support (GIC of CAD $20,635+), medical exam, and biometrics.",
    },
    {
      question: "Can I bring my spouse or dependents to Canada?",
      answer:
        "Depending on your program (e.g. Master's / Doctoral degrees or eligible professional programs), spouses may be eligible for an Open Work Permit, and minor children can study at public schools.",
    },
    {
      question: "How does the Post-Graduation Work Permit (PGWP) work?",
      answer:
        "Graduates from eligible Canadian institutions can receive a PGWP valid for up to 3 years, offering a direct pathway to permanent residence through Canadian Experience Class (CEC) and Express Entry.",
    },
  ],
  "united-kingdom": [
    {
      question: "What is a CAS letter for a UK Student Visa?",
      answer:
        "A Confirmation of Acceptance for Studies (CAS) is an electronic reference number generated by your UK university confirming your unconditional offer, course details, tuition fees, and English qualification.",
    },
    {
      question: "What is the UK Graduate Route (Post-Study Work Visa)?",
      answer:
        "The UK Graduate Route allows international students who have successfully completed an undergraduate or master's degree to stay and work (or look for work) in the UK for up to 2 years (3 years for PhD).",
    },
    {
      question: "Is a TB (Tuberculosis) test certificate mandatory for UK from India?",
      answer:
        "Yes, if you are coming from India for a stay exceeding 6 months, you must take a TB test at an approved clinic and submit the medical clearance certificate with your visa application.",
    },
  ],
  "united-states": [
    {
      question: "What is the F-1 Student Visa process for the USA?",
      answer:
        "After receiving your Form I-20 from a SEVP-certified institution, you pay the SEVIS I-901 fee ($350), complete the DS-160 online application, schedule your biometric appointment (OFC) and consular visa interview.",
    },
    {
      question: "What questions are asked in the US Visa Consular Interview?",
      answer:
        "Visa officers evaluate your academic intentions, university choice, funding sources, and strong ties to your home country. VisaEnter provides comprehensive 1-on-1 mock interviews to ensure you pass with confidence.",
    },
    {
      question: "What is OPT (Optional Practical Training) for STEM students?",
      answer:
        "STEM degree graduates in the USA are eligible for a 24-month OPT extension, allowing up to 3 years (36 months) of legal work authorization in the USA post-graduation.",
    },
  ],
  australia: [
    {
      question: "What is the Genuine Student (GS) requirement for Australia?",
      answer:
        "The Genuine Student (GS) criterion assesses your academic progression, personal circumstances, career outcomes, and value of the qualification to confirm genuine study intentions.",
    },
    {
      question: "How much financial capacity is required for Australia Student Visa Subclass 500?",
      answer:
        "Applicants must show proof of 12 months' living costs (approx. AUD $29,710), one-year tuition fees, travel expenses, and Overseas Student Health Cover (OSHC).",
    },
  ],
  dubai: [
    {
      question: "What are the benefits of the Dubai 5-Year Green / Business Visa?",
      answer:
        "The 5-Year Business / Green Visa enables self-sponsorship without a local employer, allowing you to establish companies, invest, purchase real estate, and sponsor family members with easy renewals.",
    },
    {
      question: "How fast is the Dubai Visa processing with VisaEnter?",
      answer:
        "Standard UAE tourist and business visas are processed online within 3 to 5 business days, with express 24-hour delivery options available for urgent travel needs.",
    },
  ],
};

const STEP_ROADMAP = [
  {
    step: "01",
    title: "Profile Assessment",
    duration: "Day 1 - 2",
    desc: "Evaluating academic background, gap years, language test scores, and university acceptance letters.",
    icon: UserCheck,
  },
  {
    step: "02",
    title: "Financial & SOP Prep",
    duration: "Day 3 - 5",
    desc: "Structuring blocked accounts, sponsor affidavits, bank balance certificates, and drafting SOPs.",
    icon: FileText,
  },
  {
    step: "03",
    title: "Online Form Filing",
    duration: "Day 6 - 8",
    desc: "Accurate filing on official embassy portals (VFS, TLS, ImmiAccount, DS-160) with error-free documents.",
    icon: Send,
  },
  {
    step: "04",
    title: "Biometrics & Interview",
    duration: "Day 9 - 12",
    desc: "1-on-1 mock interview preparation with senior counselors and biometric slot scheduling.",
    icon: ShieldCheck,
  },
  {
    step: "05",
    title: "Visa Grant & Departure",
    duration: "Final Stamp",
    desc: "Receiving stamped passport with near 100% approval, plus student housing & flight ticket support.",
    icon: PlaneTakeoff,
  },
];

const VISA_CATEGORY_OPTIONS = [
  { value: "Student Visa", label: "Student Visa", sub: "Bachelor's, Master's & Research", icon: "🎓" },
  { value: "Work & Employment Permit", label: "Work & Employment", sub: "Skilled Worker / Job Seeker", icon: "💼" },
  { value: "Tourist & Visitor Visa", label: "Tourist / Visitor", sub: "Tourism, Family & Business Visit", icon: "🏖️" },
  { value: "Business & Investor Visa", label: "Business & Investor", sub: "Trade, Company Setup & Golden Visa", icon: "🏢" },
  { value: "Family & Spouse Visa", label: "Family / Dependent", sub: "Spouse & Child Sponsorship", icon: "👨‍👩‍👧" },
  { value: "Visa Refusal Overturn", label: "Refusal Overturn", sub: "Re-filing & Appeal Consultation", icon: "🛡️" },
];

function CountryApplyForm({ countryName }: { countryName: string }) {
  const [form, setForm] = useState({
    name: "",
    phone: "",
    email: "",
    category: "Student Visa",
    notes: "",
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsDropdownOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const selectedCategory =
    VISA_CATEGORY_OPTIONS.find((opt) => opt.value === form.category) || VISA_CATEGORY_OPTIONS[0];

  const validateField = (field: string, value: string): string => {
    if (field === "name") {
      if (!value.trim()) return "Full name is required";
      if (value.trim().length < 2) return "Name must be at least 2 characters";
    }
    if (field === "phone") {
      if (!value.trim()) return "Phone number is required";
      const cleanPhone = value.replace(/[\s\-\+\(\)]/g, "");
      if (cleanPhone.length < 8 || !/^[0-9]+$/.test(cleanPhone)) {
        return "Please enter a valid phone number (min 8 digits)";
      }
    }
    if (field === "email") {
      if (!value.trim()) return "Email address is required";
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim())) {
        return "Please enter a valid email address";
      }
    }
    return "";
  };

  const handleBlur = (field: string) => {
    setTouched((prev) => ({ ...prev, [field]: true }));
    const errorMsg = validateField(field, form[field as keyof typeof form]);
    setErrors((prev) => ({ ...prev, [field]: errorMsg }));
  };

  const handleChange = (field: string, value: string) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    if (touched[field]) {
      const errorMsg = validateField(field, value);
      setErrors((prev) => ({ ...prev, [field]: errorMsg }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const allTouched = { name: true, phone: true, email: true };
    setTouched(allTouched);

    const newErrors: Record<string, string> = {
      name: validateField("name", form.name),
      phone: validateField("phone", form.phone),
      email: validateField("email", form.email),
    };
    setErrors(newErrors);

    const hasError = Object.values(newErrors).some((msg) => Boolean(msg));
    if (hasError) {
      toast.error("Please fill in all mandatory fields before submitting.");
      return;
    }

    setIsSubmitting(true);
    await new Promise((resolve) => setTimeout(resolve, 800));

    toast.success(`Application for ${countryName} submitted! Connecting with assigned visa counselor...`);

    const formattedMessage = `*New Visa Inquiry — ${countryName} VisaEnter*
----------------------------------------
*Applicant Name:* ${form.name.trim()}
*Phone Number:* ${form.phone.trim()}
*Email Address:* ${form.email.trim()}
*Destination:* ${countryName}
*Visa Category:* ${form.category}
*Case Notes:* ${form.notes.trim() || `Interested in ${countryName} visa checklist and step-by-step guidance.`}
----------------------------------------
Please schedule my appointment with the ${countryName} visa specialist.`;

    const whatsappUrl = `https://wa.me/918125298332?text=${encodeURIComponent(formattedMessage)}`;

    setIsSubmitting(false);
    window.open(whatsappUrl, "_blank");

    setForm({
      name: "",
      phone: "",
      email: "",
      category: "Student Visa",
      notes: "",
    });
    setTouched({});
    setErrors({});
  };

  return (
    <div className="rounded-3xl border border-sky-100 bg-white p-7 sm:p-8 shadow-xl shadow-sky-500/5 sticky top-24">
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-xl font-extrabold text-slate-900 tracking-tight">
          Apply for {countryName}
        </h3>
        <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 text-[11px] font-bold text-emerald-700">
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-ping" />
          Live Advisors
        </span>
      </div>
      <p className="text-xs text-slate-700 font-medium leading-relaxed mb-6">
        Get a personalized roadmap for your {countryName} visa application with zero delays.
      </p>

      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Full Name */}
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
            Full Name <span className="text-rose-500">*</span>
          </label>
          <div className="relative">
            <input
              type="text"
              value={form.name}
              onChange={(e) => handleChange("name", e.target.value)}
              onBlur={() => handleBlur("name")}
              placeholder="Your full name"
              className={`w-full rounded-xl border bg-slate-50/50 px-4 py-2.5 text-sm outline-none transition-all ${
                touched.name && errors.name
                  ? "border-rose-400 bg-rose-50/30 text-rose-900 focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                  : "border-slate-200 focus:border-primary focus:bg-white focus:ring-2 focus:ring-primary/20"
              }`}
            />
            {touched.name && errors.name && (
              <AlertCircle className="absolute right-3.5 top-3 h-4 w-4 text-rose-500 pointer-events-none" />
            )}
          </div>
          {touched.name && errors.name && (
            <motion.p initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }} className="mt-1 text-xs text-rose-600 font-medium">
              {errors.name}
            </motion.p>
          )}
        </div>

        {/* Phone Number */}
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
            Phone Number <span className="text-rose-500">*</span>
          </label>
          <div className="relative">
            <input
              type="tel"
              value={form.phone}
              onChange={(e) => handleChange("phone", e.target.value)}
              onBlur={() => handleBlur("phone")}
              placeholder="+91-XXXXX XXXXX"
              className={`w-full rounded-xl border bg-slate-50/50 px-4 py-2.5 text-sm outline-none transition-all ${
                touched.phone && errors.phone
                  ? "border-rose-400 bg-rose-50/30 text-rose-900 focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                  : "border-slate-200 focus:border-primary focus:bg-white focus:ring-2 focus:ring-primary/20"
              }`}
            />
            {touched.phone && errors.phone && (
              <AlertCircle className="absolute right-3.5 top-3 h-4 w-4 text-rose-500 pointer-events-none" />
            )}
          </div>
          {touched.phone && errors.phone && (
            <motion.p initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }} className="mt-1 text-xs text-rose-600 font-medium">
              {errors.phone}
            </motion.p>
          )}
        </div>

        {/* Email Address */}
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
            Email Address <span className="text-rose-500">*</span>
          </label>
          <div className="relative">
            <input
              type="email"
              value={form.email}
              onChange={(e) => handleChange("email", e.target.value)}
              onBlur={() => handleBlur("email")}
              placeholder="you@email.com"
              className={`w-full rounded-xl border bg-slate-50/50 px-4 py-2.5 text-sm outline-none transition-all ${
                touched.email && errors.email
                  ? "border-rose-400 bg-rose-50/30 text-rose-900 focus:border-rose-500 focus:ring-2 focus:ring-rose-200"
                  : "border-slate-200 focus:border-primary focus:bg-white focus:ring-2 focus:ring-primary/20"
              }`}
            />
            {touched.email && errors.email && (
              <AlertCircle className="absolute right-3.5 top-3 h-4 w-4 text-rose-500 pointer-events-none" />
            )}
          </div>
          {touched.email && errors.email && (
            <motion.p initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }} className="mt-1 text-xs text-rose-600 font-medium">
              {errors.email}
            </motion.p>
          )}
        </div>

        {/* Visa Category Custom Dropdown */}
        <div className="relative" ref={dropdownRef}>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
            Visa Category <span className="text-rose-500">*</span>
          </label>
          <button
            type="button"
            onClick={() => setIsDropdownOpen((prev) => !prev)}
            className={`w-full rounded-xl border bg-slate-50/70 hover:bg-slate-50 px-4 py-2.5 text-sm flex items-center justify-between outline-none transition-all cursor-pointer ${
              isDropdownOpen
                ? "border-primary ring-2 ring-primary/20 bg-white"
                : "border-slate-200"
            }`}
          >
            <div className="flex items-center gap-2.5 overflow-hidden text-left">
              <span className="text-base shrink-0">{selectedCategory.icon}</span>
              <span className="font-bold text-slate-900 truncate">{selectedCategory.label}</span>
              <span className="text-slate-500 text-xs hidden sm:inline truncate">({selectedCategory.sub})</span>
            </div>
            <ChevronDown
              className={`h-4 w-4 text-slate-400 shrink-0 ml-2 transition-transform duration-200 ${
                isDropdownOpen ? "rotate-180 text-primary" : ""
              }`}
            />
          </button>

          <AnimatePresence>
            {isDropdownOpen && (
              <motion.div
                initial={{ opacity: 0, y: -6, scale: 0.98 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: -6, scale: 0.98 }}
                transition={{ duration: 0.15 }}
                className="absolute z-50 left-0 right-0 mt-1.5 bg-white rounded-2xl border border-sky-100 shadow-2xl overflow-hidden py-1.5 max-h-60 overflow-y-auto"
              >
                {VISA_CATEGORY_OPTIONS.map((opt) => {
                  const isSelected = form.category === opt.value;
                  return (
                    <button
                      key={opt.value}
                      type="button"
                      onClick={() => {
                        handleChange("category", opt.value);
                        setIsDropdownOpen(false);
                      }}
                      className={`w-full px-4 py-2 text-left flex items-center justify-between hover:bg-sky-50/80 transition-colors cursor-pointer text-sm ${
                        isSelected ? "bg-sky-50 text-primary font-bold" : "text-slate-700"
                      }`}
                    >
                      <div className="flex items-center gap-2.5 min-w-0">
                        <span className="text-base shrink-0">{opt.icon}</span>
                        <div className="truncate">
                          <p className={`truncate leading-snug ${isSelected ? "font-bold text-primary" : "font-medium text-slate-900"}`}>
                            {opt.label}
                          </p>
                          <p className="text-[11px] text-slate-500 truncate leading-snug">
                            {opt.sub}
                          </p>
                        </div>
                      </div>
                      {isSelected && <Check className="h-4 w-4 text-primary shrink-0 ml-2" />}
                    </button>
                  );
                })}
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Case Notes / Questions */}
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
            Case Notes / Questions
          </label>
          <textarea
            rows={3}
            value={form.notes}
            onChange={(e) => setForm((prev) => ({ ...prev, notes: e.target.value }))}
            placeholder="Course intake, travel dates, or previous rejection history..."
            className="w-full rounded-xl border border-slate-200 bg-slate-50/50 px-4 py-2.5 text-sm outline-none focus:border-primary focus:bg-white focus:ring-2 focus:ring-primary/20 resize-none text-slate-900"
          />
        </div>

        {/* Submit button */}
        <button
          type="submit"
          disabled={isSubmitting}
          className="w-full rounded-xl gradient-primary py-3 text-sm font-bold text-white shadow-md hover:scale-[1.02] transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-75"
        >
          {isSubmitting ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" /> Submitting Request...
            </>
          ) : (
            <>
              <Send className="h-4 w-4" /> Book Free Assessment
            </>
          )}
        </button>
      </form>
    </div>
  );
}

export const Route = createFileRoute("/countries/$slug")({
  loader: ({ params }) => {
    const country = COUNTRIES_DATA.find((c) => c.slug === params.slug);
    if (!country) throw notFound();
    return { country };
  },
  head: ({ loaderData }) => ({
    meta: loaderData
      ? [
          { title: loaderData.country.metaTitle },
          { name: "description", content: loaderData.country.metaDescription },
          { property: "og:title", content: loaderData.country.metaTitle },
          { property: "og:description", content: loaderData.country.metaDescription },
        ]
      : [{ title: "Country Visa Services — VisaEnter" }],
  }),
  component: CountryPage,
  notFoundComponent: () => (
    <PageLayout>
      <div className="py-40 text-center">
        <h1 className="text-4xl font-bold">Country Not Found</h1>
        <p className="mt-2 text-muted-foreground">The requested country guide does not exist.</p>
        <Link
          to="/"
          className="mt-6 inline-block rounded-full gradient-primary px-6 py-2.5 text-sm font-bold text-white"
        >
          Back to Home
        </Link>
      </div>
    </PageLayout>
  ),
});

function CountryPage() {
  const { country } = Route.useLoaderData<{ country: CountryData }>();
  const otherCountries = COUNTRIES_DATA.filter((c) => c.slug !== country.slug).slice(0, 4);
  const heroImage = COUNTRY_HERO_IMAGES[country.slug] || defaultHeroImg;
  const faqs = COUNTRY_SPECIFIC_FAQS[country.slug] || [
    {
      question: `What is the processing time for a ${country.name} visa?`,
      answer: `Processing typically takes ${country.processingTime}. VisaEnter handles complete document preparation to avoid any embassy delays.`,
    },
    {
      question: `What are the financial requirements for ${country.name}?`,
      answer: `You must show proof of financial sufficiency (bank statements, sponsor affidavits, or blocked funds) covering your tuition and living costs.`,
    },
    {
      question: `Does VisaEnter provide interview and appointment booking for ${country.name}?`,
      answer: `Yes! We manage appointment scheduling at VFS/embassy portals, provide mock interview coaching, and structure your document dossier.`,
    },
  ];

  return (
    <PageLayout>
      {/* 1. Hero with Single-Line Gradient Title & Balanced Font Size */}
      <section className="relative h-[60vh] min-h-[440px] max-h-[580px] w-full overflow-hidden bg-slate-950 flex items-center">
        <div
          className="absolute inset-0 bg-cover bg-center transition-all duration-700"
          style={{ backgroundImage: `url(${heroImage})` }}
          aria-hidden
        />
        {/* Darkening Gradient Overlay */}
        <div
          className="absolute inset-0"
          style={{
            background:
              "linear-gradient(180deg, rgba(15, 23, 42, 0.72) 0%, rgba(15, 23, 42, 0.9) 100%)",
          }}
          aria-hidden
        />

        <div className="relative z-10 mx-auto max-w-4xl px-6 text-white pt-10 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-4xl mx-auto"
          >
            {/* Country Category Pill */}
            <span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3.5 py-1 text-xs font-semibold uppercase tracking-[0.2em] backdrop-blur-md mb-4">
              <span className="h-2 w-2 rounded-full animate-pulse bg-emerald-400" />
              Immigration &amp; Visa Advisory
            </span>

            {/* Single-Line Gradient Title with Decreased Balanced Size */}
            <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-extrabold tracking-tight leading-tight md:whitespace-nowrap">
              <span className="text-white">{country.name} </span>
              <span className="text-gradient">Visa Services</span>
            </h1>

            {/* Subtitle */}
            <p className="mt-3 text-sm md:text-base text-white/85 leading-relaxed font-light max-w-3xl mx-auto md:whitespace-nowrap">
              {country.tagline} — Expert assistance with near 100% approval rate by VisaEnter.
            </p>

            {/* Quick action buttons */}
            <div className="mt-6 flex flex-wrap justify-center items-center gap-4">
              <a
                href="#apply-form"
                className="inline-flex items-center gap-2 rounded-full gradient-primary px-6 py-3 text-xs md:text-sm font-bold text-white shadow-lg hover:shadow-xl hover:scale-105 transition-all"
              >
                Start Your Application <ArrowRight className="h-4 w-4" />
              </a>
              <a
                href={CONTACT_INFO.whatsappHref}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-full border border-white/30 bg-white/10 px-6 py-3 text-xs md:text-sm font-bold text-white backdrop-blur-md hover:bg-white/20 transition-all"
              >
                Chat on WhatsApp
              </a>
            </div>
          </motion.div>
        </div>
      </section>

      {/* 2. Key Metrics Bar */}
      <section className="py-10 bg-gradient-to-b from-sky-50/40 via-white to-sky-50/20 border-y border-slate-100">
        <div className="mx-auto max-w-7xl px-6">
          <div className="grid gap-6 sm:grid-cols-3">
            {[
              { icon: Clock, label: "Processing Time", value: country.processingTime },
              { icon: CreditCard, label: "Approx. Visa Fee", value: country.visaFee },
              { icon: Calendar, label: "Visa Validity", value: country.validityPeriod },
            ].map((m, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 15 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                whileHover={{ y: -4 }}
                className="group rounded-3xl border border-sky-100 bg-white p-6 shadow-xs flex items-center gap-5 hover:shadow-md hover:border-primary/40 transition-all"
              >
                <div className="grid h-13 w-13 shrink-0 place-items-center rounded-2xl bg-[#0099ff] text-white shadow-md shadow-sky-500/20 group-hover:scale-115 transition-transform duration-300">
                  <m.icon className="h-6 w-6 text-white stroke-[2.2]" />
                </div>
                <div>
                  <div className="text-xs font-bold uppercase text-slate-500 tracking-wider">
                    {m.label}
                  </div>
                  <div className="text-lg font-extrabold text-slate-900 mt-0.5">{m.value}</div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* 3. Main Content Grid (Overview, Pathways, Checklist & Apply Form) */}
      <section className="py-20 bg-white">
        <div className="mx-auto max-w-7xl px-6">
          {/* Centered Section Header */}
          <div className="mx-auto max-w-4xl text-center mb-14">
            <span className="inline-flex items-center gap-2 rounded-full border border-sky-500/20 bg-sky-50 px-4 py-1.5 text-xs font-extrabold uppercase tracking-[0.25em] text-primary shadow-sm mb-3">
              <Sparkles className="h-3.5 w-3.5 text-primary" /> COMPREHENSIVE GUIDANCE
            </span>
            <h2 className="text-xl sm:text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight md:whitespace-nowrap">
              About <span className="text-gradient">{country.name} Visa Services</span>
            </h2>
            <p className="mt-3 text-slate-700 font-medium text-sm md:text-base max-w-3xl mx-auto leading-relaxed md:whitespace-nowrap">
              {country.tagline} — Professional end-to-end processing with near 100% approval success.
            </p>
          </div>

          <div className="grid gap-12 lg:grid-cols-3 items-start">
            {/* Left 2 Cols: Details & Requirements */}
            <div className="lg:col-span-2 space-y-12">
              <div>
                <h3 className="text-lg sm:text-xl font-extrabold text-slate-900 mb-3">
                  Strategic Visa Advisory for {country.name}
                </h3>
                <p className="text-slate-700 font-medium leading-relaxed text-sm md:text-base">
                  {country.description}
                </p>
              </div>

              {/* Visa Pathways for this Country */}
              <div>
                <h3 className="text-lg sm:text-xl font-extrabold text-slate-900 mb-5">
                  Available Visa Pathways for {country.name}
                </h3>
                <div className="grid gap-4 sm:grid-cols-2">
                  {[
                    {
                      icon: GraduationCap,
                      title: "Student Visa",
                      desc: "For undergraduate, master's, diploma and research admissions with work permits.",
                    },
                    {
                      icon: Briefcase,
                      title: "Work & Employment Permit",
                      desc: "For skilled professionals, job seekers, and intra-company transferees.",
                    },
                    {
                      icon: Globe2,
                      title: "Tourist & Visitor Visa",
                      desc: "For leisure, vacation, visiting friends, and short-term cultural exploration.",
                    },
                    {
                      icon: Award,
                      title: "Business & Investor Visa",
                      desc: "For corporate meetings, trade fairs, company setup, and multi-entry investor visas.",
                    },
                  ].map((path, idx) => (
                    <motion.div
                      key={idx}
                      initial={{ opacity: 0, y: 15 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: idx * 0.08 }}
                      whileHover={{ y: -5, scale: 1.02 }}
                      className="group rounded-2xl border border-sky-100 bg-white p-5 shadow-xs hover:shadow-lg hover:border-primary/50 transition-all duration-300"
                    >
                      <div className="grid h-11 w-11 place-items-center rounded-xl bg-[#0099ff] text-white shadow-md shadow-sky-500/20 mb-3 transition-transform duration-300 ease-out group-hover:scale-120 group-hover:shadow-xl group-hover:shadow-sky-500/35">
                        <path.icon className="h-5 w-5 text-white stroke-[2.2]" />
                      </div>
                      <h4 className="font-bold text-slate-900 group-hover:text-primary transition-colors text-sm sm:text-base">
                        {path.title}
                      </h4>
                      <p className="mt-1.5 text-xs text-slate-700 font-medium leading-relaxed">
                        {path.desc}
                      </p>
                    </motion.div>
                  ))}
                </div>
              </div>

              {/* Requirements Checklist with Animated Staggered Cards */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-lg sm:text-xl font-extrabold text-slate-900">
                    Key Requirements &amp; Checklist
                  </h3>
                  <span className="text-xs font-bold text-primary bg-sky-50 border border-sky-100 px-3 py-1 rounded-full">
                    Official Checklist
                  </span>
                </div>
                <p className="text-xs text-slate-700 font-medium leading-relaxed mb-5">
                  Our immigration experts assist you in gathering, verifying, and translating all necessary documents to build a solid case.
                </p>

                <div className="space-y-3">
                  {country.requirements.map((req, idx) => (
                    <motion.div
                      key={idx}
                      initial={{ opacity: 0, x: -15 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: idx * 0.06 }}
                      whileHover={{ x: 6, scale: 1.01 }}
                      className="group flex items-start gap-3.5 p-4 rounded-2xl border border-sky-100 bg-white shadow-xs hover:border-primary/50 hover:shadow-md transition-all duration-200"
                    >
                      <div className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-sky-50 text-[#0099ff] group-hover:bg-[#0099ff] group-hover:text-white transition-colors duration-200 mt-0.5">
                        <CheckCircle2 className="h-4 w-4 stroke-[2.4]" />
                      </div>
                      <span className="text-sm font-semibold text-slate-800 leading-snug group-hover:text-slate-950 transition-colors">
                        {req}
                      </span>
                    </motion.div>
                  ))}
                </div>
              </div>

              {/* Trust Banner Callout */}
              <div className="rounded-3xl gradient-primary p-7 sm:p-8 text-white shadow-xl">
                <div className="flex items-center gap-3 mb-2">
                  <ShieldCheck className="h-6 w-6" />
                  <span className="text-sm font-bold uppercase tracking-wider">
                    VisaEnter Guarantee
                  </span>
                </div>
                <h3 className="text-xl sm:text-2xl font-extrabold">15+ Years Handling {country.name} Cases</h3>
                <p className="mt-2 text-sm text-white/90 leading-relaxed font-medium">
                  Whether you have previous visa denials, gap years, or complex financial profiles, our Bangalore team crafts a strategic dossier to maximize your approval probability.
                </p>
                <div className="mt-6">
                  <a
                    href={CONTACT_INFO.phoneHref}
                    className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-2.5 text-sm font-bold text-slate-900 shadow hover:bg-white/95 hover:scale-105 transition-all"
                  >
                    <Phone className="h-4 w-4 text-primary" /> Call Specialist: {CONTACT_INFO.phone}
                  </a>
                </div>
              </div>
            </div>

            {/* Right Col: Interactive Consultation / Application Form */}
            <div id="apply-form" className="lg:sticky lg:top-24">
              <CountryApplyForm countryName={country.name} />
            </div>
          </div>
        </div>
      </section>

      {/* 4. STEP-BY-STEP PATHWAY (Decreased Height Cards with Default Electric Blue Icons) */}
      <section className="py-24 bg-gradient-to-b from-sky-50/40 via-white to-sky-50/20 relative overflow-hidden border-y border-slate-100">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mx-auto max-w-4xl text-center mb-14">
            <span className="inline-flex items-center gap-2 rounded-full border border-sky-500/20 bg-sky-50 px-4 py-1.5 text-xs font-extrabold uppercase tracking-[0.25em] text-primary shadow-sm mb-3">
              <Sparkles className="h-3.5 w-3.5 text-primary" /> STEP-BY-STEP PATHWAY
            </span>
            <h2 className="text-xl sm:text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight md:whitespace-nowrap text-center">
              How We Process Your <span className="text-gradient">{country.name} Visa</span>
            </h2>
            <p className="mt-3 text-slate-700 font-medium text-sm md:text-base max-w-3xl mx-auto leading-relaxed md:whitespace-nowrap text-center">
              A transparent, structured 5-step roadmap ensuring fast turnaround and zero delays.
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5 relative">
            {STEP_ROADMAP.map((st, i) => (
              <motion.div
                key={st.step}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{
                  duration: 0.4,
                  delay: i * 0.08,
                }}
                whileHover={{
                  y: -6,
                  scale: 1.02,
                }}
                className="group relative rounded-2xl border border-sky-100 bg-white p-4 sm:p-5 shadow-xs hover:shadow-lg hover:border-primary/50 transition-all duration-300 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <span className="inline-flex items-center justify-center rounded-full px-2.5 py-0.5 text-[11px] font-extrabold text-white gradient-primary shadow-xs">
                      Step {st.step}
                    </span>
                    <span className="text-[10px] font-bold uppercase rounded-full bg-sky-50 text-primary border border-sky-100 px-2 py-0.5">
                      {st.duration}
                    </span>
                  </div>

                  <div className="grid h-11 w-11 place-items-center rounded-xl bg-[#0099ff] text-white shadow-md shadow-sky-500/20 mb-3 transition-transform duration-300 ease-out group-hover:scale-120 group-hover:shadow-xl group-hover:shadow-sky-500/35">
                    <st.icon className="h-5 w-5 text-white stroke-[2.2]" />
                  </div>

                  <h4 className="font-bold text-sm sm:text-base text-slate-900 group-hover:text-primary transition-colors leading-snug mb-1.5">
                    {st.title}
                  </h4>
                  <p className="text-xs text-slate-700 font-medium leading-relaxed">
                    {st.desc}
                  </p>
                </div>

                <div className="mt-4 pt-2.5 border-t border-slate-100 flex items-center justify-between text-[11px] font-bold text-primary">
                  <span>Milestone {st.step}</span>
                  <span className="group-hover:translate-x-1 transition-transform">→</span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* 5. Country Specific FAQs */}
      <section className="py-24 bg-white">
        <div className="mx-auto max-w-4xl px-6">
          <div className="mx-auto max-w-4xl text-center mb-14">
            <span className="inline-flex items-center gap-2 rounded-full border border-sky-500/20 bg-sky-50 px-4 py-1.5 text-xs font-extrabold uppercase tracking-[0.25em] text-primary shadow-sm mb-3">
              <Sparkles className="h-3.5 w-3.5 text-primary" /> FREQUENTLY ASKED
            </span>
            <h2 className="text-xl sm:text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight md:whitespace-nowrap text-center">
              Common Questions on <span className="text-gradient">{country.name} Visas</span>
            </h2>
            <p className="mt-3 text-slate-700 font-medium text-sm md:text-base max-w-3xl mx-auto leading-relaxed md:whitespace-nowrap text-center">
              Get clarity on documentation, funds, embassy rules, and visa timelines.
            </p>
          </div>

          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, idx) => (
              <AccordionItem
                key={idx}
                value={`faq-${idx}`}
                className="rounded-2xl border border-sky-100 bg-white px-6 py-1 shadow-xs data-[state=open]:shadow-md data-[state=open]:border-primary/40 transition-all"
              >
                <AccordionTrigger className="text-left font-bold text-base text-slate-900 hover:text-primary transition-colors">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-sm text-slate-700 font-medium leading-relaxed pt-2 pb-4">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* 6. Other Destinations (Cards with Destination Photos) */}
      <section className="py-24 bg-gradient-to-b from-sky-50/40 via-white to-sky-50/20 border-t border-slate-100">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mx-auto max-w-4xl text-center mb-14">
            <span className="inline-flex items-center gap-2 rounded-full border border-sky-500/20 bg-sky-50 px-4 py-1.5 text-xs font-extrabold uppercase tracking-[0.25em] text-primary shadow-sm mb-3">
              <Sparkles className="h-3.5 w-3.5 text-primary" /> EXPLORE MORE
            </span>
            <h2 className="text-xl sm:text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight md:whitespace-nowrap text-center">
              Explore Other <span className="text-gradient">Global Destinations</span>
            </h2>
            <p className="mt-3 text-slate-700 font-medium text-sm md:text-base max-w-3xl mx-auto leading-relaxed md:whitespace-nowrap text-center">
              Expert visa guidance across top study, work, and migration countries worldwide.
            </p>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {otherCountries.map((c) => {
              const cImg = COUNTRY_HERO_IMAGES[c.slug] || defaultHeroImg;
              return (
                <Link
                  key={c.slug}
                  to="/countries/$slug"
                  params={{ slug: c.slug }}
                  className="rounded-3xl border border-sky-100 bg-white overflow-hidden shadow-xs hover:shadow-lg hover:border-primary/40 hover:-translate-y-1.5 transition-all flex flex-col justify-between group"
                >
                  {/* Photo Header */}
                  <div className="relative h-40 overflow-hidden">
                    <img
                      src={cImg}
                      alt={c.name}
                      className="h-full w-full object-cover group-hover:scale-110 transition-transform duration-500"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent" />
                    <div className="absolute top-3 left-3">
                      <span className="rounded-full bg-white/20 backdrop-blur-md border border-white/20 px-2.5 py-0.5 text-[10px] font-extrabold text-white uppercase tracking-wider">
                        Visa Services
                      </span>
                    </div>
                    <div className="absolute bottom-2.5 left-3.5 right-3.5">
                      <h4 className="font-extrabold text-lg text-white drop-shadow">
                        {c.name}
                      </h4>
                    </div>
                  </div>

                  {/* Body */}
                  <div className="p-5 flex-1 flex flex-col justify-between">
                    <p className="text-xs text-slate-700 font-medium line-clamp-2">{c.tagline}</p>
                    <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-xs font-bold text-primary">
                      <span>Explore Requirements</span>
                      <span className="group-hover:translate-x-1 transition-transform">→</span>
                    </div>
                  </div>
                </Link>
              );
            })}
          </div>
        </div>
      </section>
    </PageLayout>
  );
}
