/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisasByPolicyRouteImport } from './routes/visas-by-policy'
import { Route as VisasByCountryRouteImport } from './routes/visas-by-country'
import { Route as PassportIndexRouteImport } from './routes/passport-index'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisaCategoriesSlugRouteImport } from './routes/visa-categories.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as CoachingSlugRouteImport } from './routes/coaching.$slug'

const VisasByPolicyRoute = VisasByPolicyRouteImport.update({
  id: '/visas-by-policy',
  path: '/visas-by-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const VisasByCountryRoute = VisasByCountryRouteImport.update({
  id: '/visas-by-country',
  path: '/visas-by-country',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportIndexRoute = PassportIndexRouteImport.update({
  id: '/passport-index',
  path: '/passport-index',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaCategoriesSlugRoute = VisaCategoriesSlugRouteImport.update({
  id: '/visa-categories/$slug',
  path: '/visa-categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingSlugRoute = CoachingSlugRouteImport.update({
  id: '/coaching/$slug',
  path: '/coaching/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/passport-index': typeof PassportIndexRoute
  '/visas-by-country': typeof VisasByCountryRoute
  '/visas-by-policy': typeof VisasByPolicyRoute
  '/coaching/$slug': typeof CoachingSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/visa-categories/$slug': typeof VisaCategoriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/passport-index': typeof PassportIndexRoute
  '/visas-by-country': typeof VisasByCountryRoute
  '/visas-by-policy': typeof VisasByPolicyRoute
  '/coaching/$slug': typeof CoachingSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/visa-categories/$slug': typeof VisaCategoriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/passport-index': typeof PassportIndexRoute
  '/visas-by-country': typeof VisasByCountryRoute
  '/visas-by-policy': typeof VisasByPolicyRoute
  '/coaching/$slug': typeof CoachingSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/visa-categories/$slug': typeof VisaCategoriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/passport-index'
    | '/visas-by-country'
    | '/visas-by-policy'
    | '/coaching/$slug'
    | '/countries/$slug'
    | '/services/$slug'
    | '/visa-categories/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/passport-index'
    | '/visas-by-country'
    | '/visas-by-policy'
    | '/coaching/$slug'
    | '/countries/$slug'
    | '/services/$slug'
    | '/visa-categories/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/passport-index'
    | '/visas-by-country'
    | '/visas-by-policy'
    | '/coaching/$slug'
    | '/countries/$slug'
    | '/services/$slug'
    | '/visa-categories/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PassportIndexRoute: typeof PassportIndexRoute
  VisasByCountryRoute: typeof VisasByCountryRoute
  VisasByPolicyRoute: typeof VisasByPolicyRoute
  CoachingSlugRoute: typeof CoachingSlugRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  VisaCategoriesSlugRoute: typeof VisaCategoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visas-by-policy': {
      id: '/visas-by-policy'
      path: '/visas-by-policy'
      fullPath: '/visas-by-policy'
      preLoaderRoute: typeof VisasByPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visas-by-country': {
      id: '/visas-by-country'
      path: '/visas-by-country'
      fullPath: '/visas-by-country'
      preLoaderRoute: typeof VisasByCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-index': {
      id: '/passport-index'
      path: '/passport-index'
      fullPath: '/passport-index'
      preLoaderRoute: typeof PassportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa-categories/$slug': {
      id: '/visa-categories/$slug'
      path: '/visa-categories/$slug'
      fullPath: '/visa-categories/$slug'
      preLoaderRoute: typeof VisaCategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching/$slug': {
      id: '/coaching/$slug'
      path: '/coaching/$slug'
      fullPath: '/coaching/$slug'
      preLoaderRoute: typeof CoachingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PassportIndexRoute: PassportIndexRoute,
  VisasByCountryRoute: VisasByCountryRoute,
  VisasByPolicyRoute: VisasByPolicyRoute,
  CoachingSlugRoute: CoachingSlugRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  VisaCategoriesSlugRoute: VisaCategoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
